packages:
  sm-cd-oled-base: !include packages/abr-smo-c3-base.yaml

substitutions:
  device_name: abr-smo-c3-b
  friendly_name: "ABRobot SuperMini OLED ESP32-C3 B"
  api_key: !secret abr-smo-c3-b-key
  bme_temp_filters:
    - offset: 0.0
  #    - calibrate_polynomial:
  #        degree: 1
  #        datapoints:
  bme_hum_filters:
    - offset: 0.0
#    - calibrate_polynomial:
#        degree: 1
#        datapoints:
