packages:
  common-options: !include packages/common-ble-sc.yaml

substitutions:
  device_name: "athom-rf-ir-remote"
  friendly_name: "Athom RF-IR Remote"
  api_key: !secret athom-rf-ir-remote-key

esp32:
  board: esp32dev
  variant: esp32
  flash_size: 8MB
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      # @grigi found in testing that these options resulted in better responsiveness.
      # BLE 4.2 is supported by ALL ESP32 boards that have bluetooth, the original and derivatives.
      CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y
      # Extend the watchdog timeout, so the device reboots if the device appears locked up for over 10 seconds.
      CONFIG_ESP_TASK_WDT_TIMEOUT_S: "10"

api:
  services:
    - service: send_raw_command
      variables:
        command: int[]
      then:
        - remote_transmitter.transmit_raw:
            code: !lambda 'return command;'

remote_receiver:
  - pin:
      number: GPIO19
      inverted: true
    dump: rc_switch
    tolerance: 25%
    id: rf_receiver

  - pin:
      number: GPIO33
      inverted: true
    dump: all
    tolerance: 25%
    id: ir_receiver

remote_transmitter:
#  - pin:
#      number: GPIO18
#    # OOK modulation for RF433 — keep duty at 100%
#    carrier_duty_percent: 100%
#    non_blocking: true
#    id: rf_transmitter

  - pin:
      number: GPIO25
      inverted: false
    carrier_duty_percent: 50%
    non_blocking: true
    id: ir_transmitter

infrared:
  - platform: ir_rf_proxy
    name: IR Proxy Transmitter
    id: ir_proxy_transmitter
    remote_transmitter_id: ir_transmitter

  - platform: ir_rf_proxy
    name: IR Proxy Receiver
    id: ir_proxy_receiver
    receiver_frequency: 38kHz
    remote_receiver_id: ir_receiver

#radio_frequency:
#  - platform: ir_rf_proxy
#    name: 433MHz RF Transmitter
#    id: rf_proxy_transmitter
#    frequency: 433.92MHz
#    remote_transmitter_id: rf_transmitter
#
#  - platform: ir_rf_proxy
#    name: 433MHz RF Receiver
#    id: rf_proxy_receiver
#    frequency: 433.92MHz
#    remote_receiver_id: rf_receiver

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode:
        input: true
      inverted: true
      ignore_strapping_warning: true
    id: button1

light:
  - platform: status_led
    name: "Status LED"
    pin: GPIO27
    entity_category: diagnostic
