esphome:
  name: qtpy-s3-env
  friendly_name: "QT-Py S3 + Env"

  platformio_options:
    upload_speed: 2000000

  on_boot:
    - light.addressable_set:
         id: neopixel
         red: 25%
         green: 25%
         blue: 0%

esp32:
  variant: ESP32S3
  framework:
    type: esp-idf
  flash_size: 4MB
  cpu_frequency: 80MHz

psram:
  mode: quad
  speed: 80MHz
  ignore_not_found: false

logger:
  level: DEBUG

api:
  encryption:
    key: !secret qtpy-s3-env-key

ota:
  - platform: esphome
  # password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "QT-Py S3 Env Setup"
    password: !secret wifi_ap_password
  fast_connect: true
  use_psram: true
  on_connect:
    - light.addressable_set:
        id: neopixel
        red: 0%
        green: 25%
        blue: 0%

captive_portal:

button:
  - platform: restart
    name: "Restart"

esp32_ble:
  max_connections: 5

esp32_ble_tracker:

bluetooth_proxy:
  active: true
  connection_slots: 5

power_supply:
  - id: neopixel_power
    pin: GPIO38

light:
  - platform: esp32_rmt_led_strip
    name: "NeoPixel"
    id: neopixel
    pin: GPIO39
    power_supply: neopixel_power
    num_leds: 1
    rgb_order: GRB
    chipset: WS2812
    use_dma: true
#    effects:
#      - pulse:
#          max_brightness: 25%
#      - addressable_rainbow:
#      - addressable_twinkle:
#      - addressable_random_twinkle:

i2c:
  - id: i2c_qt
    sda: GPIO41
    scl: GPIO40
    scan: true
    frequency: 400kHz

  - id: i2c_pins
    sda: GPIO7
    scl: GPIO6
    scan: true
    frequency: 400kHz

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s

  - platform: uptime
    name: "Uptime"
    id: uptime_s
    update_interval: 60s

  - platform: bme280_i2c
    i2c_id: i2c_qt
    address: 0x76
    update_interval: 10s
    temperature:
      name: "Temperature"
      id: bme_temp
    humidity:
      name: "Humidity"
      id: bme_hum
    pressure:
      name: "Pressure"
      id: bme_pres
