packages:
  common-options: !include packages/common-ble.yaml

substitutions:
  device_name: qtpy-s3-env
  friendly_name: "QT-Py ESP32-S3 + Env Sensors"
  api_key: !secret qtpy-s3-env-key

esphome:
  on_boot:
    - light.addressable_set:
         id: neopixel
         red: 25%
         green: 25%
         blue: 0%

esp32:
  variant: ESP32S3
  flash_size: 4MB

psram:
  mode: quad
  speed: 80MHz
  ignore_not_found: false

wifi:
  use_psram: true
  on_connect:
    - light.addressable_set:
        id: neopixel
        red: 0%
        green: 25%
        blue: 0%

esp32_ble:
  max_connections: 5
  use_psram: true

bluetooth_proxy:
  connection_slots: 5
  active: true

power_supply:
  - id: neopixel_power
    pin: GPIO38

light:
  - platform: esp32_rmt_led_strip
    id: neopixel
    name: "NeoPixel"
    disabled_by_default: true
    pin: GPIO39
    power_supply: neopixel_power
    num_leds: 1
    rgb_order: GRB
    chipset: WS2812
    use_dma: true
#    effects:
#      - pulse:
#          max_brightness: 25%
#      - addressable_rainbow:
#      - addressable_twinkle:
#      - addressable_random_twinkle:

i2c:
  - id: i2c_qt
    sda: GPIO41
    scl: GPIO40
    scan: true
    frequency: 400kHz

  - id: i2c_pins
    sda: GPIO7
    scl: GPIO6
    scan: true
    frequency: 400kHz

sensor:
  - platform: internal_temperature
    name: "Internal Temperature"
    entity_category: diagnostic

  - platform: sht4x
    i2c_id: i2c_qt
    heater_max_duty: 0.01
    temperature:
      name: "Temperature (SHT4X)"
      id: sht_temp
    humidity:
      name: "Humidity"
      id: sht_hum

  - platform: spa06_i2c
    i2c_id: i2c_qt
    temperature:
      name: "Temperature (SPA06)"
      id: spa_temp
    pressure:
      name: "Pressure"
      id: spa_pres
