packages:
  common-options: !include common-ble.yaml

substitutions:
  device_name: ws-touch-lcd-147-c6
  friendly_name: "Waveshare Touch LCD 1.47 ESP32-C6"
  api_key: ${api_key}

esp32:
  variant: ESP32C3
  flash_size: 4MB
#  toolchain: esp-idf

globals:
  - id: display_on
    type: bool
    restore_value: yes
    initial_value: "true"

i2c:
  sda: GPIO5
  scl: GPIO6
  scan: True
  frequency: 400kHz

sensor:
  - platform: bme280_i2c
    address: 0x76
    update_interval: 60s
    temperature:
      name: "Temperature"
      id: bme_temp
      filters:
        ${bme_temp_filters}
    humidity:
      name: "Humidity"
      id: bme_hum
      filters:
        ${bme_hum_filters}
    pressure:
      name: "Pressure"
      id: bme_pres

binary_sensor:
  - platform: gpio
    id: left_button
    pin:
      number: GPIO09
      inverted: true
      mode: INPUT_PULLUP
      ignore_strapping_warning: true
    on_click:
      then:
        - lambda: |-
            id(display_on) = !id(display_on);
            ESP_LOGD("button", "Display: %s", id(display_on) ? "ON" : "OFF");
        - component.update: oled
    on_double_click:
      then:
        - light.toggle: light_status
        - lambda: |-
            ESP_LOGD("button", "Blue LED: %s", id(light_status).current_values.is_on() ? "ON" : "OFF");

switch:
  - platform: template
    name: "Display"
    restore_mode: RESTORE_DEFAULT_ON
    lambda: |-
      if (id(display_on)) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
      - lambda: |-
          id(display_on) = true;
          ESP_LOGD("switch", "Display: ON");
      - component.update: oled
    turn_off_action:
      - lambda: |-
          id(display_on) = false;
          ESP_LOGD("switch", "Display: OFF");
      - component.update: oled

  - platform: template
    name: "Blue LED"
    restore_mode: RESTORE_DEFAULT_ON
    lambda: |-
      return id(light_status).current_values.is_on();
    turn_on_action:
      - lambda: |-
          ESP_LOGD("switch", "Blue LED: ON");
      - light.turn_on: light_status
    turn_off_action:
      - lambda: |-
          ESP_LOGD("switch", "Blue LED: OFF");
      - light.turn_off: light_status

light:
  - platform: status_led
    id: light_status
    pin:
      number: GPIO08
      inverted: true
      ignore_strapping_warning: true

font:
  - file: "gfonts://Roboto"
    id: roboto
    size: 11

display:
  - platform: ssd1306_i2c
    model: "SSD1306 72x40"
    id: oled
    update_interval: 10s
    address: 0x3C
    rotation: 180
    lambda: |-
      if (id(display_on)) {
        float temp_fht = (id(bme_temp).state * 9 / 5) + 32;
        float hum = id(bme_hum).state;
        float pres = id(bme_pres).state;
        it.printf(0, 0, id(roboto),  "T: %.1f° F", temp_fht);
        it.printf(0, 13, id(roboto), "H: %.1f%% rh", hum);
        it.printf(0, 26, id(roboto), "P: %.1f mb", pres);
      } else {
        it.fill(COLOR_OFF);
      }
      //ESP_LOGD("sensors", "T: %.1f  H: %.1f%% rh  P: %.1f mb", temp_fht, hum, pres);
