esphome:
  name: ${dev_name}
  friendly_name: ${friendly_name}

  platformio_options:
    upload_speed: 2000000
  environment_variables:
    PLATFORMIO_BUILD_CACHE_DIR: ".pio/build-cache"

esp32:
  variant: ESP32C3
  framework:
    type: esp-idf
  flash_size: 4MB
#  toolchain: esp-idf

logger:
  level: DEBUG

globals:
  - id: display_on
    type: bool
    restore_value: yes
    initial_value: "true"

api:
  encryption:
    key: ${api_key}
  on_client_connected:
    - esp32_ble_tracker.start_scan:
        continuous: true
  on_client_disconnected:
    - esp32_ble_tracker.stop_scan:

ota:
  - platform: esphome
  # password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

button:
  - platform: restart
    name: Restart

esp32_ble_tracker:
  scan_parameters:
    continuous: false

bluetooth_proxy:
  connection_slots: 3
  active: true

i2c:
  sda: GPIO5
  scl: GPIO6
  scan: True
  frequency: 400kHz

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    id: wifi_rssi
    update_interval: 60s

  - platform: uptime
    name: "Uptime"
    id: uptime_s
    update_interval: 60s

  - platform: bme280_i2c
    address: 0x76
    update_interval: 60s
    temperature:
      name: "Temperature"
      id: bme_temp
      filters:
        ${bme_temp_filters}
    humidity:
      name: "Humidity"
      id: bme_hum
      filters:
        ${bme_hum_filters}
    pressure:
      name: "Pressure"
      id: bme_pres

binary_sensor:
  - platform: gpio
    name: "Left Button"
    id: left_button
    pin:
      number: GPIO09
      inverted: true
      mode: INPUT_PULLUP
      ignore_strapping_warning: true
    on_click:
      then:
        - lambda: |-
            id(display_on) = !id(display_on);
            ESP_LOGD("buttons", "Display: %s", id(display_on) ? "ON" : "OFF");
        - component.update: oled
    on_double_click:
      then:
        - light.toggle: light_status

switch:
  - platform: template
    name: "Display"
    restore_mode: RESTORE_DEFAULT_ON
    lambda: |-
      if (id(display_on)) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
      - lambda: |-
          id(display_on) = true;
          ESP_LOGD("buttons", "Display on: %d", id(display_on));
      - component.update: oled
    turn_off_action:
      - lambda: |-
          id(display_on) = false;
          ESP_LOGD("buttons", "Display on: %d", id(display_on));
      - component.update: oled

light:
  - platform: status_led
    name: "Blue LED"
    id: light_status
    pin:
      number: GPIO08
      inverted: true
      ignore_strapping_warning: true

font:
  - file: "gfonts://Roboto"
    id: roboto
    size: 11

display:
  - platform: ssd1306_i2c
    model: "SSD1306 72x40"
    id: oled
    update_interval: 10s
    address: 0x3C
    rotation: 180
    lambda: |-
      if (id(display_on)) {
        float temp_fht = (id(bme_temp).state * 9 / 5) + 32;
        float hum = id(bme_hum).state;
        float pres = id(bme_pres).state;
        it.printf(0, 0, id(roboto),  "T: %.1f° F", temp_fht);
        it.printf(0, 13, id(roboto), "H: %.1f%% rh", hum);
        it.printf(0, 26, id(roboto), "P: %.1f mb", pres);
      } else {
        it.fill(COLOR_OFF);
      }
      //ESP_LOGD("sensors", "T: %.1f  H: %.1f%% rh  P: %.1f mb", temp_fht, hum, pres);
