esphome:
  name: ${dev_name}
  friendly_name: ${friendly_name}

esp32:
  variant: ESP32C3
  framework:
    type: esp-idf
  flash_size: 4MB
  cpu_frequency: 80MHz

logger:
  level: DEBUG

api:
  # encryption:
  #   key: ""
  on_client_connected:
    - esp32_ble_tracker.start_scan:
        continuous: true
  on_client_disconnected:
    - esp32_ble_tracker.stop_scan:

ota:
  - platform: esphome
  # password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: ${friendly_name}
    password: !secret wifi_ap_password
  fast_connect: true

web_server:
  ota: false
  local: true

captive_portal:

button:
  - platform: restart
    name: Restart

esp32_ble_tracker:
  scan_parameters:
    continuous: false

bluetooth_proxy:
  connection_slots: 3
  active: true

i2c:
  sda: GPIO5
  scl: GPIO6
  scan: True

sensor:
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 60s

  - platform: bme280_i2c
    address: 0x76
    update_interval: 60s
    temperature:
      name: "Temperature"
      id: bme_temp
    humidity:
      name: "Humidity"
      id: bme_hum
    pressure:
      name: "Pressure"
      id: bme_pres

globals:
  - id: click_type_text
    type: std::string
    restore_value: no
    initial_value: ""

  - id: click_type_map
    type: std::map<std::string, std::string>
    restore_value: no
    initial_value: '{ {"single", "Single Click"}, {"double", "Double Click"}, {"long", "Long Press"} }'

script:
  - id: button_click_handler
    parameters:
      click_type: string
    then:
      - globals.set:
          id: click_type_text
          value: !lambda 'return id(click_type_map).count(click_type) ? id(click_type_map)[click_type] : "Unknown";'
      # Send HA event
      - homeassistant.event:
          event: esphome.button_click
          data:
            device: ${dev_name}
            type: ${click_type}
            text: ${click_type_text}
      - logger.log: 
          format: "%s"
          args: [ 'id(click_type_text).c_str()' ]
      # Clear display after a delay
      - script.execute: clear_click_type_timer

  - id: clear_click_type_timer
    mode: restart   # timer restarts if called again
    then:
      - delay: 5s
      - globals.set:
          id: click_type_text
          value: '""'

text:
  - platform: template
    name: "Line 1"
    optimistic: true
    id: custom_message
    mode: text
    initial_value: "Hello World"

# HA helper
# Create a "helper" in HA with Entity ID "input_text.esp_text".
# Text value of the helper will be shown on the OLED display
text_sensor:
  - platform: homeassistant
    name: "ESP Text"
    id: esp_text_helper
    entity_id: input_text.esp_text
    on_value:
      then:
        - logger.log:
            format: "ESP Text: %s"
            args: ["x.c_str()"]

light:
  - platform: status_led
    name: "Blue LED"
    id: light_status
    pin:
      number: GPIO08
      inverted: true

binary_sensor:
  - platform: gpio
    name: "Boo Button"
    id: binary_boo
    pin:
      number: GPIO09
      inverted: true
      mode: INPUT_PULLUP

    on_multi_click:
    - timing:
        - ON for at most 0.8s
        - OFF for at most 0.3s
        - ON for at most 0.8s
        - OFF for at least 0.2s
      then:
        - script.execute:
            id: button_click_handler
            click_type: 'double'
    - timing:
        - ON for 0.8s to 5s
        - OFF for at least 0.4s
      then:
        - script.execute:
            id: button_click_handler
            click_type: 'long'
        - light.toggle: light_status
    - timing:
        - ON for at most 0.8s
        - OFF for at least 0.4s
      then:
        - script.execute:
            id: button_click_handler
            click_type: 'single'

font:
  - file: "gfonts://Roboto"
    id: roboto
    size: 11

display:
  - platform: ssd1306_i2c
    model: "SSD1306 72x40"
    update_interval: 0.5s
    address: 0x3C
    contrast: 70%
    rotation: 180
    lambda: |-
      it.printf(0, 0, id(roboto), "%s", id(custom_message).state.c_str());
      it.print(0, 13, id(roboto), id(esp_text_helper).state.c_str());
      it.print(0, 26, id(roboto), id(click_type_text).c_str());
