packages:
  base: !include packages/ws-geek-base.yaml
  common-options: !include packages/common.yaml

substitutions:
  device_name: ws-geek-c6
  friendly_name: "Waveshare Geek ESP32-C6"
  api_key: !secret ws-geek-c6-key
  backlight_pin: GPIO6
  sda_pin: GPIO7
  scl_pin:
    number: GPIO8
    ignore_strapping_warning: true
  clk_pin: GPIO1
  mosi_pin: GPIO2
  button_pin:
    number: GPIO9
    inverted: true
    mode: INPUT_PULLUP
    ignore_strapping_warning: true

esp32:
  variant: ESP32C6
  flash_size: 16MB

display:
  - platform: mipi_spi
    id: !extend lcd
    model: st7789v
    dc_pin: GPIO3
    reset_pin:
      number: GPIO4
      ignore_strapping_warning: true
    cs_pin:
      number: GPIO5
      ignore_strapping_warning: true
