packages:
  common-options: !include common-ble.yaml
  ws-s3-epaper: !include ws-s3-epaper-154-base.yaml

substitutions:
  device_name: ws-s3-epaper-154-usb
  friendly_name: "Waveshare ESP32-S3 ePaper 1.54 USB"
  api_key: !secret ws-s3-epaper-154-key

globals:
  - id: !extend stay_awake
    initial_value: "true"

esp32_ble:
  use_psram: true
