packages:
  common-options: !include common-ble.yaml
  ws-s3-epaper: !include ws-s3-epaper-154-base.yaml

substitutions:
  device_name: ws-s3-epaper-154-usb
  friendly_name: "Waveshare ESP32-S3 ePaper 1.54 USB"
  api_key: !secret ws-s3-epaper-154-key

globals:
  - id: !extend stay_awake
    initial_value: "true"

esp32_ble:
  use_psram: true

deep_sleep:
  id: deep_sleep_1
  sleep_duration: 15min

display:
  - id: !extend epaper_display
    lambda: |-
      id(epd_power).turn_on();
      int top1 = 0;
      int top2 = 20;
      int top3 = 50;
      int top4 = 80;
      int bot3 = 160;
      int bot2 = 180;
      int bot1 = 200;
      int left = 0;
      int middle = 100;
      int right = 200;

      it.fill(COLOR_OFF);

      it.print(middle, top1, id(font_fancy_small), COLOR_ON, TextAlign::TOP_CENTER, "Back Yard");
      it.printf(left + 10, top2, id(font_fancy_medium), COLOR_ON, TextAlign::TOP_LEFT, "%.1f°F", id(backyard_temperature).state);
      it.printf(right - 10, top2, id(font_fancy_medium), COLOR_ON, TextAlign::TOP_RIGHT, "%.0f%%RH", id(backyard_humidity).state);
      
      it.print(middle, top3, id(font_fancy_large), COLOR_ON, TextAlign::TOP_CENTER, "Pool");
      it.printf(middle, top4, id(font_fancy_xxlarge), COLOR_ON, TextAlign::TOP_CENTER, "%.1f°F", id(pool_temperature).state);

      if (id(ha_time).now().is_valid()) {
      it.strftime(left, bot2, id(font_xsmall), COLOR_ON, TextAlign::BOTTOM_LEFT, "%H:%M", id(ha_time).now());
      it.strftime(left, bot1, id(font_xsmall), COLOR_ON, TextAlign::BOTTOM_LEFT, "%Y-%m-%d", id(ha_time).now());
      } else {
      it.print(left, bot2, id(font_xsmall), COLOR_ON, TextAlign::BOTTOM_LEFT, "?Time?");
      it.print(left, bot1, id(font_xsmall), COLOR_ON, TextAlign::BOTTOM_LEFT, "?Date?");
      }

      it.print(right, bot1, id(font_xsmall), COLOR_ON, TextAlign::BOTTOM_RIGHT, id(wake_status).c_str());
      id(epd_power).turn_off();
