packages:
#  common-options: !include packages/common.yaml
  common-options: !include packages/common-ble.yaml
  ws-s3-epaper: !include packages/ws-s3-epaper-154-base.yaml

substitutions:
  device_name: ws-s3-epaper-154-usb
  friendly_name: "Waveshare ESP32-S3 ePaper 1.54 USB"
  api_key: !secret ws-s3-epaper-154-key

globals:
  - id: !extend stay_awake
    initial_value: "true"

esp32_ble:
  use_psram: true

deep_sleep:
  id: deep_sleep_1
  sleep_duration: 15min

display:
  - id: !extend epaper_display
    update_interval: 5min
    rotation: 0
    lambda: |-
      id(epd_power).turn_on();
      int top1 = 0;
      int top2 = 12;
      int line1 = top2 + id(font_fancy_xlarge).get_baseline() + 5;
      int mid1 = 82;
      int mid2 = 139;
      int bot1 = 200;
      int line2 = bot1 - id(font_small).get_ascender() - 3;
      int left = 3;
      int middle = 100;
      int right = 197;

      it.fill(COLOR_OFF);

      it.print(middle, top1, id(font_small), COLOR_ON, TextAlign::TOP_CENTER, "BACK YARD");
      it.printf(left + 9, top2, id(font_fancy_xlarge), COLOR_ON, TextAlign::TOP_LEFT, "%.1f°", id(backyard_temperature).state);
      it.printf(right - 9, top2, id(font_fancy_xlarge), COLOR_ON, TextAlign::TOP_RIGHT, "%.0f%%", id(backyard_humidity).state);
      
      it.filled_rectangle(0, line1, 200, 2);
      
      it.print(middle, mid1, id(font_fancy_xlarge), COLOR_ON, TextAlign::CENTER, "POOL");
      it.printf(middle, mid2, id(font_fancy_xxlarge), COLOR_ON, TextAlign::CENTER, "%.1f°", id(pool_temperature).state);
      
      it.filled_rectangle(0, line2, 200, 2);

      if (id(ha_time).now().is_valid()) {
        it.strftime(left, bot1, id(font_xsmall), COLOR_ON, TextAlign::BOTTOM_LEFT, "%Y-%m-%d %H:%M", id(ha_time).now());
      } else {
        it.print(left, bot1, id(font_xsmall), COLOR_ON, TextAlign::BOTTOM_LEFT, "?Date? ?Time?");
      }

      it.print(right, bot1, id(font_xsmall), COLOR_ON, TextAlign::BOTTOM_RIGHT, id(wake_status).c_str());
      id(epd_power).turn_off();
