packages:
  common-options: !include common.yaml
  ws-s3-epaper: !include ws-s3-epaper-154-base.yaml

substitutions:
  device_name: ws-epaper-154-s3-batt
  friendly_name: "Waveshare ESP32-S3 ePaper 1.54 Battery"
  api_key: !secret ws-tiny-epd-s3-key

esp32:
  cpu_frequency: 80MHz

globals:
  - id: !extend stay_awake
    initial_value: "false"
