packages:
  common-options: !include common-ble-sc.yaml

substitutions:
  device_name: abr-smo-c3-base
  friendly_name: "ABRobot SuperMini OLED ESP32-C3 Base"
  api_key: ${api_key}

esp32:
  variant: ESP32C3
  flash_size: 4MB

globals:
  - id: led_was_on
    type: bool
    restore_value: yes
    initial_value: 'false'

interval:
  interval: 1min
  then:
    - if:
        condition:
          lambda: |-
            int hour = id(ha_time).now().hour;
            return (hour < 6 || hour > 23);
        then:
          lambda: |-
            id(led_was_on) = id(oled).is_on();
            id(status_light).turn_off();
        else:
          lambda: |-
            if (id(led_was_on)) {
              id(status_light).turn_on();
            }

i2c:
  sda: GPIO5
  scl: GPIO6
  frequency: 400kHz

sensor:
  - platform: bme280_i2c
    address: 0x76
    update_interval: 60s
    temperature:
      name: "Temperature"
      id: bme_temp
      filters:
        ${bme_temp_filters}
    humidity:
      name: "Humidity"
      id: bme_hum
      filters:
        ${bme_hum_filters}
    pressure:
      name: "Pressure"
      id: bme_pres

  - platform: combination
    id: bme_temp_f
    type: linear
    sources:
      - source: bme_temp
        coefficient: 1.0
    filters:
      - lambda: return x * (9.0 / 5.0) + 32.0;
    unit_of_measurement: "°F"

binary_sensor:
  - platform: gpio
    id: left_button
    pin:
      number: GPIO09
      inverted: true
      mode: INPUT_PULLUP
      ignore_strapping_warning: true
    on_click:
      then:
        - light.toggle: display_light
    on_double_click:
      then:
        - light.toggle: status_light

output:
  - platform: template
    id: display_output
    type: float
    min_power: 0.01
    # the oled doesn't get noticeably brighter above 66%
    max_power: 0.66
    write_action:
      lambda: 'id(oled).set_contrast(state);'

light:
  - platform: monochromatic
    id: display_light
    name: "Display"
    output: display_output
    icon: mdi:television
    entity_category: config
    restore_mode: RESTORE_DEFAULT_OFF
    initial_state:
      color_mode: BRIGHTNESS
      brightness: 50%
    on_turn_on:
      lambda: 'id(oled).turn_on();'
    on_turn_off:
      lambda: 'id(oled).turn_off();'

  - platform: status_led
    id: status_light
    name: "Status LED"
    icon: mdi:led-outline
    entity_category: config
    restore_mode: RESTORE_DEFAULT_OFF
    pin:
      number: GPIO08
      inverted: true
      ignore_strapping_warning: true

font:
  - file:
      type: gfonts
      family: "Ubuntu Mono"
    id: ubuntu_mono
    size: 15

display:
  - platform: ssd1306_i2c
    model: "SSD1306 72x40"
    id: oled
    rotation: 180
    lambda: |-
      it.printf(36,  0, id(ubuntu_mono), TextAlign::TOP_CENTER, "%.1f °F", id(bme_temp_f).state);
      it.printf(36, 13, id(ubuntu_mono), TextAlign::TOP_CENTER, "%.1f %%H", id(bme_hum).state);
      it.printf(36, 26, id(ubuntu_mono), TextAlign::TOP_CENTER, "%4.f mb", id(bme_pres).state);
