packages:
  common-options: !include common-ble.yaml

substitutions:
  device_name: ws-touch-lcd-147-c6
  friendly_name: "Waveshare Touch LCD 1.47 ESP32-C6"
  api_key: ${api_key}

esp32:
  variant: ESP32C3
  flash_size: 4MB

i2c:
  sda: GPIO5
  scl: GPIO6
  scan: True
  frequency: 400kHz

sensor:
  - platform: bme280_i2c
    address: 0x76
    update_interval: 60s
    temperature:
      name: "Temperature"
      id: bme_temp
      filters:
        ${bme_temp_filters}
    humidity:
      name: "Humidity"
      id: bme_hum
      filters:
        ${bme_hum_filters}
    pressure:
      name: "Pressure"
      id: bme_pres

binary_sensor:
  - platform: gpio
    id: left_button
    pin:
      number: GPIO09
      inverted: true
      mode: INPUT_PULLUP
      ignore_strapping_warning: true
    on_click:
      then:
        - lambda: |-
            id(oled).is_on() ? id(oled).turn_off(): id(oled).turn_on();
        - component.update: oled
    on_double_click:
      then:
        - light.toggle: light_status

switch:
  - platform: template
    name: "Display ON⁄OFF"
    restore_mode: RESTORE_DEFAULT_ON
    lambda: return id(oled).is_on();
    turn_on_action:
      - lambda: id(oled).turn_on();
    turn_off_action:
      - lambda: id(oled).turn_off();

number:
  - platform: template
    name: "Contrast"
    min_value: 1
    max_value: 10
    step: 1
    # above 50% doesn't seem to do much, so treat that as the max
    lambda: return id(oled).get_contrast() * 5.0;
    set_action:
      then:
        lambda: id(oled).set_contrast(x / 5.0);


light:
  - platform: status_led
    id: light_status
    name: "Status LED"
    disabled_by_default: true
    restore_mode: RESTORE_DEFAULT_OFF
    pin:
      number: GPIO08
      inverted: true
      ignore_strapping_warning: true

font:
  - file:
      type: gfonts
      family: "Ubuntu Mono"
    id: ubuntu_mono
    size: 15

display:
  - platform: ssd1306_i2c
    model: "SSD1306 72x40"
    id: oled
    rotation: 180
    # above 50% doesn't seem to do much, so treating that as max
    contrast: 50%
    lambda: |-
      float temp_fht = (id(bme_temp).state * 9 / 5) + 32;
      it.printf(36,  0, id(ubuntu_mono), TextAlign::TOP_CENTER, "%.1f °F", temp_fht);
      it.printf(36, 13, id(ubuntu_mono), TextAlign::TOP_CENTER, "%.1f %%H", id(bme_hum).state);
      it.printf(36, 26, id(ubuntu_mono), TextAlign::TOP_CENTER, "%4.f mb", id(bme_pres).state);
      //ESP_LOGD("sensors", "%.1 °F %.1f %%H %4.f mb", temp_fht, id(bme_hum).state, id(bme_pres).state);
